### ISSUE TITLE
add hardwareBackPress

### ISSUE THREAD

**Issue by fera765** [Sharcoux/react-unavigation#1]
For better navigation criteria how to add hardwareBackPress?

**Comment by Sharcoux** [comment]
Actually, you just need to stack the values of active slide in an array to be your memory.
Like this:

```javascript 
const history = useRef([])
const navigate = useCallback(slide => {
  history.current.push(slide) 
  setActive(slide)
}, []) 
const goBack = useCallback(() => {
  setActive(history.current.pop())
}, []) 
```

**Comment by Sharcoux** [comment]
In my personal use cases, the active slide depends on the state of my application, so I don't need that.
I think that the main use case for this would be pagination of a list of data. I don't think that it should be used in other cases.
